[program:messenger-worker]
command=php /var/www/bin/console messenger:consume async --time-limit=3600
process_name=%(program_name)s_%(process_num)02d
; Number of processes which will handle messenger probably the limit for improving perfomance is something near 16
numprocs=16
startsecs=0
autostart=true
autorestart=true
startretries=10
user=www-data
environment=MESSENGER_CONSUMER_NAME="%(program_name)s_%(process_num)02d"

; Avoid supervisor timeouts when the worker is stopping gracefully
stopwaitsecs=60

[supervisord]
logfile=/var/log/supervisor/supervisord.log
pidfile=/var/run/supervisord.pid
nodaemon=true